#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "Wait..."
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "-"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "Wait..."
done
echo -e "Okay"
tput cnorm
}
clear
echo -e "SlowDNS Installer"
echo ""
echo -e "Downloading utilities..."
echo ""
fun_att () {
apt install ncurses-utils -y
mkdir /etc/slowdns
cd /etc/slowdns
wget https://github.com/nokyaselpon/slow/raw/main/dns-server; chmod +x dns-server
wget https://raw.githubusercontent.com/nokyaselpon/slow/main/remove-slow; chmod +x remove-slow
wget https://raw.githubusercontent.com/nokyaselpon/slow/main/slowdns-info; chmod +x slowdns-info
wget https://raw.githubusercontent.com/nokyaselpon/slow/main/slowdns-ssh; chmod +x slowdns-ssh
wget https://raw.githubusercontent.com/nokyaselpon/slow/main/slowdns; chmod +x slowdns; cp slowdns /bin/
wget https://raw.githubusercontent.com/nokyaselpon/slow/main/stopdns; chmod +x stopdns
}
fun_bar 'fun_att'

echo -e "Configuring dns settings.."
echo ""
fun_dnscf () {
sudo systemctl disable systemd-resolved.service && sudo systemctl stop systemd-resolved.service && sudo mv /etc/resolv.conf /etc/resolv.conf.bkp && echo "nameserver 1.1.1.1" > /etc/resolv.conf
sudo systemctl enable systemd-resolved.service && sudo systemctl start systemd-resolved.service
sleep 2
}
fun_bar 'fun_dnscf'

clear
echo -e "SLOWDNS INSTALLER"

echo ""
echo -e "Installed Completely!"
echo ""
echo -e "To open the menu, use the command: slowdns"
cd
rm install
