#!/bin/bash
clear
slowdns () {
    echo -e "SLOW DNS GLOBE/TM & STS"
    echo ""
    echo -e "1.)Install SlowDNS SSH"
    echo -e "2.)See information"
    echo -e "3.)Start SlowDNS"
    echo -e "4.)Restart SlowDNS"
    echo -e "5.)STOP SlowDNS"
    echo -e "6.)Remove SlowDNS"
    echo -e "0.)EXIT"
    echo ""
    echo -ne "What do you want to do? :" && read option
    case $option in
    1) Option1 ;;
    2) Option2 ;;
    3) Option3 ;;
    4) Option4 ;;
    5) Option5 ;;
    6) Option6 ;;
    0) Sair ;;
    *) "Enter valid option" ; echo ; slowdns ;;
    esac
    }

Option1 () {
    clear
    bash /etc/slowdns/slowdns-ssh
}

Option2 () {
    clear
    bash /etc/slowdns/slowdns-info
}

Option3 () {
    clear
    bash /etc/slowdns/startdns
}

Option4 () {
    clear
    bash /etc/slowdns/restartdns
}

Option5 () {
    clear
    bash /etc/slowdns/stopdns
}

Option6 () {
     clear
    bash /etc/slowdns/stopdns
    bash /etc/slowdns/remove-slow
}

Sair() {
    clear
    exit
}
clear
slowdns
