#!/bin/bash
echo -e "SLOWDNS INFORMATION"
echo ""
echo -ne "Your domain nameserver: " && cat /etc/slowdns/infons
echo ""
echo -ne "Your public key: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mTERMUX COMMAND:\033[0m curl -sO https://github.com/nokyaselpon/slow/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo ""
read -p "Press ENTER to return to menu"
slowdns
