#!/bin/bash
clear
slowdns () {
    echo -e "SLOW DNS GLOBE/TM & STS"
    echo ""
    echo -e "Install SlowDNS SSH"
    echo -e "See information"
    echo -e "Start SlowDNS"
    echo -e "Restart SlowDNS"
    echo -e "STOP SlowDNS"
    echo -e "Remove SlowDNS"
    echo -e "EXIT"
    echo ""
    echo -ne "\033[0;36mWhat do you want to do?:\0033[m " && read option
    case $option in
    1) Option1 ;;
    2) Option2 ;;
    3) Option3 ;;
    4) Option4 ;;
    5) Option5 ;;
    6) Option6 ;;
    0) Sair ;;
    *) "Invalid option" ; echo ; slowdns ;;
    esac
    }

Option1 () {
    clear
    bash /etc/slowdns/slowdns-ssh
}

Option2 () {
    clear
    bash /etc/slowdns/slowdns-info
}

Option3 () {
    clear
    bash /etc/slowdns/startdns
}

Option4 () {
    clear
    bash /etc/slowdns/restartdns
}

Option5 () {
    clear
    bash /etc/slowdns/stopdns
}

Option6 () {
     clear
    bash /etc/slowdns/stopdns
    bash /etc/slowdns/remove-slow
}

Sair() {
    clear
    exit
}
clear
slowdns
